public enum EPageType
{
    NONE,
    
    SCREEN_DIRECTION,
    SCREEN_GENERALPROMPTSCREEN,
    SCREEN_IMAGECHANGE,
    SCREEN_DRAGDROP,
    SCREEN_PROFILE,
    SCREEN_VIDEO,
    SCREEN_CHAT,
    SCREEN_RESTART,

    MAX,
}